name = light_pollution
description = Simulates light pollution: sky glow, star reduction, and night-vision effects near large light source clusters.
min_minetest_version = 5.6.0
optional_depends = default, fire, mcl_core, mcl_fire, mcl_torches, mcl_nether
